### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by jiayizhg** [jiayizhg/smart-meeting-system#20]
**Describe the bug**
After creating a router to connect to the new scheduling page, we are unable to log in with google and fetch google calendar events.

**To Reproduce**
1. Go to 'http://localhost:8080/scheduling'
2. Click on 'Authorize'
4. See error in console

**Expected behavior**
Should still be able to log in with google, get calendar events and log out

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**

**Comment by jiayizhg** [comment]
fixed

**Comment by YuminWang18** [comment]
It took a long time to fix.
