### ISSUE TITLE
Not able to properly delete a meeting/event

### ISSUE THREAD

**Issue by jiayizhg** [jiayizhg/smart-meeting-system#40]
**Describe the bug**
Tried to delete an meeting, the meeting is not showing on the dashboard but is still showing on Google calendar

**To Reproduce**
1. Go to Dashboard
2. Click on a meeting on the calendar
3. Click on the delete button 

**Expected behavior**
The meeting should be removed from both the dashboard and user's Google calendar

**Comment by YuminWang18** [comment]
Already done.

**Comment by jiayizhg** [comment]
resolved.
